IF OBJECT_ID('[Person].[usp_GetPerson]') IS NOT NULL
	DROP PROCEDURE [Person].[usp_GetPerson];

GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_NULLS ON
GO
CREATE PROCEDURE [Person].[usp_GetPerson]
AS
SELECT * FROM dbo.Person
GO
